Add files via upload
CSUEB-CS401-Summer2021-Group3/CRM pull request #10
Opened 2021-07-20 16:45 UTC by dargonjz

2021-07-20 22:39 UTC, nkrone-csueb commented
What exactly is this?

2021-07-20 23:15 UTC, dargonjz commented
The file on github?
Its what I have so far on the gui
I'll tried to get more done

On Tue, Jul 20, 2021, 16:13 Jacki Zhong ***@***.***> wrote:

> The file on github?
> Its what I have so far on the gui
> I'll tried to get more done
>
> On Tue, Jul 20, 2021, 15:40 nkrone-csueb ***@***.***> wrote:
>
>> What exactly is this?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/CSUEB-CS401-Summer2021-Group3/CRM/pull/10#issuecomment-883751957>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ALZVESG2SHH3Z2IIZR4GFSLTYX3MHANCNFSM5AWFQFFQ>
>> .
>>
>

2021-07-20 23:56 UTC, nkrone-csueb commented
Okay

2021-07-21 00:02 UTC, nkrone-csueb requested changes
You should have a issue created so we can keep track of what work is being done. Also, your commit message is to vague: "add files to upload" tells everyone nothing about this file aside from the fact that you're just uploading it to git.

A better commit message would be: "initial client gui" that way, when anyone first reviews the code, they have an understanding of what this file is attempting to accomplish.

Please review the suggestions I listed. Overall, it's a step in the right direction so good work.

2021-07-21 00:02 UTC, nkrone-csueb commented on zCRM.java
> +//	private JFrame frame;
Remove all these

2021-07-21 00:02 UTC, nkrone-csueb commented on zCRM.java
> +		JButton addButton = new JButton("Add New DVD");
Remove references to DVD

2021-07-21 00:02 UTC, nkrone-csueb commented on zCRM.java
> +
GUI should be separated out and placed inside the package (edu.cs401.group3.crm) 

GUI caller script (with the static main) should import and call the GUI library

2021-07-21 00:03 UTC, nkrone-csueb commented on zCRM.java
> +//	private JFrame frame;
review the commented out items that are not pertinent to the code. Commented out lines shouldn't be in code that's going to be merged.

2021-07-21 00:04 UTC, nkrone-csueb commented on zCRM.java
> +		JButton addButton = new JButton("Add New DVD");
This isn't a big deal really but if you're gonna copy paste code from previous work, at least remove references to it.

2021-07-21 00:04 UTC, nkrone-csueb commented on zCRM.java
> +
A better explanation would be having a Class called "CRMCLient" that calls the GUI library and runs it.

2021-07-21 21:25 UTC, closed without merging